server.servlet.encoding.force-response: true

chat:
  max-number-of-rooms: 100000
  number-of-ages: 6
  junior-in-each-room: 4
  senior-in-each-room: 1
  second-each-game-phase: 10

topic:
  number-of-topics: 7
  topics:
    - id: 0
      topic: 키오스크를 사용하는 방법 (이어말하기)
    - id: 1
      topic: KTX표 예매하는 방법 (이어말하기)
    - id: 2
      topic: 자신이 쓰고 있는 AI 스피커에 대한 장점 말하기
    - id: 3
      topic: 은행 ATM기에서 돈을 입금/출금하는 방법
    - id: 4
      topic: 카카오택시 사용하는 방법 / 장단점
    - id: 5
      topic: 배달의 민족을 사용하면서 주소를 잘못 지정해서 오배송이 났던 경험
    - id: 6
      topic: 다양한 모바일 금융서비스 앱의 장단점 비교와 사용자 경험에 따른 추천 사례